---
# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: CC0-1.0
#
# Configuration for yamllint CLI tool
#
# See https://yamllint.readthedocs.io

extends: default

rules:
  document-start: disable
  line-length:
    max: 88
    level: error
